const dataPeserta = [
    { id: "1000000", nama: "Muhammad Fathir Fahrezy", posisi: "Ketua Pelaksana", status: "LULUS" },
    { id: "8040100", nama: "Dilla Puspita Ramadhani", posisi: "", status: "" },
    { id: "8040204", nama: "Asri Nafsiah", posisi: "", status: "" },
    { id: "8040308", nama: "Rizki Yanuar Gunawan", posisi: "", status: "" },
    { id: "8040412", nama: "Muhammad Nur Rizqi Ramadhani", posisi: "", status: "" },
    { id: "8040516", nama: "Keysya Laura Wazariska", posisi: "", status: "" },
    { id: "8040620", nama: "Akbar Bagus Sri Zena", posisi: "", status: "" },
    { id: "8040724", nama: "Kharissa Salsabila", posisi: "", status: "" },
    { id: "8040828", nama: "Salma Nabila Nur Fitri", posisi: "", status: "" },
    { id: "8040932", nama: "Olivia Fadilah", posisi: "", status: "" },
    { id: "8041036", nama: "MIRZA NAUFAL RAZAK", posisi: "", status: "" },
    { id: "8041140", nama: "DINA USWATUN KHASANAH", posisi: "", status: "" },
    { id: "8041244", nama: "Re'fandi Indra Maulana", posisi: "", status: "" },
    { id: "8041348", nama: "Nisrina Zahra Nafiska", posisi: "", status: "" },
    { id: "8041452", nama: "Ilham Kurnia Ramadhan", posisi: "", status: "" },
    { id: "8041556", nama: "Yolanda Rasya", posisi: "", status: "" },
    { id: "8041660", nama: "Pauline cantika fautri", posisi: "", status: "" },
    { id: "8041764", nama: "Nayla Nilam Endra Pramana Putri", posisi: "", status: "" },
    { id: "8041868", nama: "Galang Aditya Wibowo", posisi: "", status: "" },
    { id: "8050100", nama: "Benedikta Chandra Ekaristi", posisi: "", status: "" },
    { id: "8050204", nama: "Annisa Ramadhani", posisi: "", status: "" },
    { id: "8060100", nama: "Dhafa Wahyu Pratama", posisi: "", status: "" },
    { id: "8060204", nama: "Aditya Bagus Hanafi", posisi: "", status: "" },
    { id: "8060308", nama: "Aulia Nur Aina", posisi: "", status: "" },
    { id: "8060412", nama: "Dimas Dwi Febriyanto", posisi: "", status: "" },
    { id: "8060516", nama: "Nabihah Yatnaning Jati", posisi: "", status: "" },
    { id: "8070100", nama: "Rachmat Hidayat", posisi: "", status: "" },
    { id: "8070204", nama: "Arindra Iqbaluna Kholifatu Rachman", posisi: "", status: "" },
    { id: "8070308", nama: "Nugraheni Wigaring Tyas", posisi: "", status: "" },
    { id: "8070412", nama: "Naufal Aqila Faza", posisi: "", status: "" },
    { id: "8070516", nama: "Azlilatun Khasanah", posisi: "", status: "" },
    { id: "8070620", nama: "Aisa Mulia Rahmah", posisi: "", status: "" },
    { id: "8080100", nama: "Asfa Rohmatul 'Afifah", posisi: "", status: "" },
    { id: "8080204", nama: "Syafa Dwi Azzahra", posisi: "", status: "" },
    { id: "8080308", nama: "Khairul Nizam", posisi: "", status: "" },
    { id: "8080412", nama: "Atika Nur Cahyani", posisi: "", status: "" },
    { id: "8080516", nama: "Akhdan Dzamar Azimas Putra", posisi: "", status: "" },
    { id: "8080620", nama: "ZERVINDA MEGA DAYU", posisi: "", status: "" },
    { id: "8080724", nama: "Maylinda Rosari", posisi: "", status: "" },
    { id: "8080828", nama: "Isnaeni Choeri Wicaksana", posisi: "", status: "" },
    { id: "8080932", nama: "Renita Damayanti Khasanah", posisi: "", status: "" },
    { id: "8081036", nama: "Elsya Putri Widyaningrum", posisi: "", status: "" },
    { id: "8081140", nama: "Eva Aulia Lathifah Sutarno", posisi: "", status: "" },
    { id: "8081244", nama: "Almas Caesarina Rahmawati", posisi: "", status: "" },
    { id: "8081348", nama: "Dewi Maryani", posisi: "", status: "" },
    { id: "8081452", nama: "Ulung Jihan Hilmi Fadil", posisi: "", status: "" },
    { id: "8081556", nama: "Hafsah Bhekti Kinasih", posisi: "", status: "" },
    { id: "8081660", nama: "Mutiara Kinantiyasih", posisi: "", status: "" },
    { id: "8081764", nama: "A'mala Rizqi Tsaniatul Khusna", posisi: "", status: "" },
    { id: "E010003", nama: "Haikhal ihsan mu'ammar", posisi: "", status: "" },
    { id: "E010001", nama: "Raina Tiara Nugraheni", posisi: "", status: "" },
    { id: "E010004", nama: "Dafa Rifaul Fajri Rizki Ramadhani", posisi: "", status: "" },
    { id: "E010002", nama: "Barqah Ramdhani", posisi: "", status: "" },
    { id: "8090100", nama: "Lulu Innuha Khosyia Robbah", posisi: "", status: "" },
    { id: "8090204", nama: "Ibnu Syamsul Ma’arif", posisi: "", status: "" },
    { id: "E020002", nama: "Kin Dzakira", posisi: "", status: "" },
    { id: "E020001", nama: "Fanessa Dhantiana Sari", posisi: "", status: "" },
    { id: "E020003", nama: "Faishal Farras Faturrahman", posisi: "", status: "" }
]


// TIDAK LULUS or LULUS
