const dataPeserta = [
    { id: "8040100", nama: "Dilla Puspita Ramadhani", posisi: "Staff Acara", status: "Lulus" },
    { id: "8040204", nama: "Asri Nafsiah", posisi: "Staff Perlengkapan", status: "Lulus" },
    { id: "8040308", nama: "Rizki Yanuar Gunawan", posisi: "Staff Acara", status: "Lulus" },
    { id: "8040412", nama: "Muhammad Nur Rizqi Ramadhani", posisi: "Staff Perlengkapan", status: "Lulus" },
    { id: "8040516", nama: "Keysya Laura Wazariska", posisi: "Staff Acara", status: "Lulus" },
    { id: "8040620", nama: "Akbar Bagus Sri Zena", posisi: "Staff Perlengkapan", status: "Lulus" },
    { id: "8040724", nama: "Kharissa Salsabila", posisi: "Staff Konsumsi", status: "Lulus" },
    { id: "8040828", nama: "Salma Nabila Nur Fitri", posisi: "Wakil Koor Bendahara", status: "Lulus" },
    { id: "8040932", nama: "Olivia Fadilah", posisi: "", status: "Tidak Lulus" },
    { id: "8041036", nama: "Mirza Naufal Razak", posisi: "Wakil Koor Lapangan", status: "Lulus" },
    { id: "8041140", nama: "Dina Uswatun Khasanah", posisi: "Staff Humas", status: "Lulus" },
    { id: "8041244", nama: "Re'fandi Indra Maulana", posisi: "Staff PDD", status: "Lulus" },
    { id: "8041348", nama: "Nisrina Zahra Nafiska", posisi: "Staff Perlengkapan", status: "Lulus" },
    { id: "8041452", nama: "Ilham Kurnia Ramadhan", posisi: "Wakil Koor Perlengkapan", status: "Lulus" },
    { id: "8041556", nama: "Yolanda Rasya", posisi: "Staff Humas", status: "Lulus" },
    { id: "8041660", nama: "Pauline Cantika Fautri", posisi: "Staff Humas", status: "Lulus" },
    { id: "8041764", nama: "Nayla Nilam Endra Pramana Putri", posisi: "", status: "Tidak Lulus" },
    { id: "8041868", nama: "Galang Aditya Wibowo", posisi: "Staff Sponsorship", status: "Lulus" },
    { id: "8050100", nama: "Benedikta Chandra Ekaristi", posisi: "Staff PDD", status: "Lulus" },
    { id: "8050204", nama: "Annisa Ramadhani", posisi: "Staff Sponsorship", status: "Lulus" },
    { id: "8060100", nama: "Dhafa Wahyu Pratama", posisi: "Staff Lapangan", status: "Lulus" },
    { id: "8060204", nama: "Aditya Bagus Hanafi", posisi: "Wakil Koor Humas", status: "Lulus" },
    { id: "8060308", nama: "Aulia Nur Aina", posisi: "Staff Konsumsi", status: "Lulus" },
    { id: "8060412", nama: "Dimas Dwi Febriyanto", posisi: "Staff Lapangan", status: "Lulus" },
    { id: "8060516", nama: "Nabihah Yatnaning Jati", posisi: "Staff Lapangan", status: "Lulus" },
    { id: "8070100", nama: "Rachmat Hidayat", posisi: "Wakil Koor Acara", status: "Lulus" },
    { id: "8070204", nama: "Arindra Iqbaluna Kholifatu Rachman", posisi: "Staff Lapangan", status: "Lulus" },
    { id: "8070308", nama: "Nugraheni Wigaring Tyas", posisi: "", status: "Tidak Lulus" },
    { id: "8070412", nama: "Naufal Aqila Faza", posisi: "Staff PDD", status: "Lulus" },
    { id: "8070516", nama: "Azlilatun Khasanah", posisi: "", status: "Tidak Lulus" },
    { id: "8070620", nama: "Aisa Mulia Rahmah", posisi: "Staff Humas", status: "Lulus" },
    { id: "8080100", nama: "Asfa Rohmatul 'Afifah", posisi: "Wakil Koor Sponsorship", status: "Lulus" },
    { id: "8080204", nama: "Syafa Dwi Azzahra", posisi: "", status: "Tidak Lulus" },
    { id: "8080308", nama: "Khairul Nizam", posisi: "Wakil Koor Try Out", status: "Lulus" },
    { id: "8080412", nama: "Atika Nur Cahyani", posisi: "Staff PDD", status: "Lulus" },
    { id: "8080516", nama: "Akhdan Dzamar Azimas Putra", posisi: "", status: "Tidak Lulus" },
    { id: "8080620", nama: "Zervinda Mega Dayu", posisi: "Staff PDD", status: "Lulus" },
    { id: "8080724", nama: "Maylinda Rosari", posisi: "Staff Try Out", status: "Lulus" },
    { id: "8080828", nama: "Isnaeni Choeri Wicaksana", posisi: "Staff Try Out", status: "Lulus" },
    { id: "8080932", nama: "Renita Damayanti Khasanah", posisi: "Staff Try Out", status: "Lulus" },
    { id: "8081036", nama: "Elsya Putri Widyaningrum", posisi: "Staff Sektretaris", status: "Lulus" },
    { id: "8081140", nama: "Eva Aulia Lathifah Sutarno", posisi: "Staff Sektretaris", status: "Lulus" },
    { id: "8081244", nama: "Almas Caesarina Rahmawati", posisi: "Staff Sponsorship", status: "Lulus" },
    { id: "8081348", nama: "Dewi Maryani", posisi: "Staff Konsumsi", status: "Lulus" },
    { id: "8081452", nama: "Ulung Jihan Hilmi Fadil", posisi: "Staff Lapangan", status: "Lulus" },
    { id: "8081556", nama: "Hafsah Bhekti Kinasih", posisi: "Wakil Koor Sektretaris", status: "Lulus" },
    { id: "8081660", nama: "Mutiara Kinantiyasih", posisi: "", status: "Tidak Lulus" },
    { id: "8081764", nama: "A'mala Rizqi Tsaniatul Khusna", posisi: "Staff Konsumsi", status: "Lulus" },
    { id: "E010003", nama: "Haikhal Ihsan Mu'ammar", posisi: "", status: "Tidak Lulus" },
    { id: "E010001", nama: "Raina Tiara Nugraheni", posisi: "Staff Acara", status: "Lulus" },
    { id: "E010004", nama: "Dafa Rifaul Fajri Rizki Ramadhani", posisi: "", status: "Tidak Lulus" },
    { id: "E010002", nama: "Barqah Ramdhani", posisi: "Staff Perlengkapan", status: "Lulus" },
    { id: "8090100", nama: "Lulu Innuha Khosyia Robbah", posisi: "Staff Try Out", status: "Lulus" },
    { id: "8090204", nama: "Ibnu Syamsul Ma’arif", posisi: "Staff Sponshorship", status: "Lulus" },
    { id: "E020002", nama: "Kin Dzakira", posisi: "", status: "Tidak Lulus" },
    { id: "E020001", nama: "Fanessa Dhantiana Sari", posisi: "Staff Bendahara", status: "Lulus" },
    { id: "E020003", nama: "Faishal Farras Faturrahman", posisi: "", status: "Tidak Lulus" }
]


// TIDAK LULUS or LULUS
